name: build

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release, Debug]
        cpp_standard: [20, 23]
    runs-on: ${{ matrix.os }}
    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      BUILD_DIR: ${{ github.workspace }}/build
      CMAKE_BUILD_PARALLEL_LEVEL: 4

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.VCPKG_ROOT }}
            ~/.cache/vcpkg
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Cache CMake build
        uses: actions/cache@v4
        with:
          path: ${{ env.BUILD_DIR }}
          key: ${{ runner.os }}-${{ matrix.build_type }}-cmake-${{ hashFiles('CMakeLists.txt', '**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.build_type }}-cmake-

      - name: Install system package
        shell: bash
        run: sudo apt install autoconf autoconf-archive automake libtool
      
      - name: Set VCPKG Triplet
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "VCPKG_TARGET_TRIPLET=x64-windows" >> $GITHUB_ENV
          elif [ "$RUNNER_OS" == "Linux" ]; then
            echo "VCPKG_TARGET_TRIPLET=x64-linux" >> $GITHUB_ENV
          else
            if [ "$(uname -m)" == "arm64" ]; then
              echo "VCPKG_TARGET_TRIPLET=arm64-osx" >> $GITHUB_ENV
            else
              echo "VCPKG_TARGET_TRIPLET=x64-osx" >> $GITHUB_ENV
            fi
          fi

      - name: Configure CMake
        shell: bash
        run: |
          cmake -S . -B $BUILD_DIR \
            -DBBSTRADER_BUILD_TESTS=ON \
            -DBBSTRADER_CXX_STANDARD=${{ matrix.cpp_standard }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
            -DVCPKG_TARGET_TRIPLET=$VCPKG_TARGET_TRIPLET

      - name: Build
        shell: bash
        run: cmake --build $BUILD_DIR --config ${{ matrix.build_type }}
        
      - name: Run tests
        shell: bash
        run: ctest --test-dir $BUILD_DIR --output-on-failure --build-config ${{ matrix.build_type }}
